"""Add hms_raw table and raw schema

Revision ID: 4bb831eaf52f
Revises: ee15494d51ff
Create Date: 2025-03-25 18:26:38.968280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb831eaf52f'
down_revision: Union[str, None] = 'ee15494d51ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hms',
    sa.Column('faerslunumer', sa.String(), nullable=False),
    sa.Column('emnr', sa.String(), nullable=False),
    sa.Column('skjalanumer', sa.String(), nullable=False),
    sa.Column('fastnum', sa.String(), nullable=False),
    sa.Column('heimilisfang', sa.String(), nullable=True),
    sa.Column('postnr', sa.String(), nullable=True),
    sa.Column('heinum', sa.String(), nullable=True),
    sa.Column('svfn', sa.String(), nullable=False),
    sa.Column('sveitarfelag', sa.String(), nullable=False),
    sa.Column('utgdag', sa.String(), nullable=False),
    sa.Column('thinglystdags', sa.String(), nullable=False),
    sa.Column('kaupverd', sa.String(), nullable=False),
    sa.Column('fasteignamat', sa.String(), nullable=False),
    sa.Column('fasteignamat_gildandi', sa.String(), nullable=True),
    sa.Column('fyrirhugad_fasteignamat', sa.String(), nullable=True),
    sa.Column('brunabotamat_gildandi', sa.String(), nullable=True),
    sa.Column('byggar', sa.String(), nullable=False),
    sa.Column('fepilog', sa.String(), nullable=False),
    sa.Column('einflm', sa.String(), nullable=False),
    sa.Column('lod_flm', sa.String(), nullable=True),
    sa.Column('lod_flmein', sa.String(), nullable=True),
    sa.Column('fjherb', sa.String(), nullable=True),
    sa.Column('tegund', sa.String(), nullable=False),
    sa.Column('fullbuid', sa.String(), nullable=False),
    sa.Column('onothaefur_samningur', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('faerslunumer', 'fastnum', name=op.f('pk_hms')),
    sa.UniqueConstraint('faerslunumer', 'fastnum', name='uq_faerslunumer_fastnum'),
    schema='raw'
    )
    op.create_index(op.f('ix_raw_hms_faerslunumer'), 'hms', ['faerslunumer'], unique=False, schema='raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_hms_faerslunumer'), table_name='hms', schema='raw')
    op.drop_table('hms', schema='raw')
    # ### end Alembic commands ###
