"""Add hms_raw table and raw schema

Revision ID: ee15494d51ff
Revises: 069b9c691fa6
Create Date: 2025-03-25 18:16:05.678502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee15494d51ff'
down_revision: Union[str, None] = '069b9c691fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade and create schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS raw;")  # schema creation explicitly added

    op.create_table('hms_raw',
    sa.Column('faerslunumer', sa.String(), nullable=False),
    sa.Column('emnr', sa.String(), nullable=False),
    sa.Column('skjalanumer', sa.String(), nullable=False),
    sa.Column('fastnum', sa.String(), nullable=False),
    sa.Column('heimilisfang', sa.String(), nullable=True),
    sa.Column('postnr', sa.String(), nullable=True),
    sa.Column('heinum', sa.String(), nullable=True),
    sa.Column('svfn', sa.String(), nullable=False),
    sa.Column('sveitarfelag', sa.String(), nullable=False),
    sa.Column('utgdag', sa.String(), nullable=False),
    sa.Column('thinglystdags', sa.String(), nullable=False),
    sa.Column('kaupverd', sa.String(), nullable=False),
    sa.Column('fasteignamat', sa.String(), nullable=False),
    sa.Column('fasteignamat_gildandi', sa.String(), nullable=True),
    sa.Column('fyrirhugad_fasteignamat', sa.String(), nullable=True),
    sa.Column('brunabotamat_gildandi', sa.String(), nullable=True),
    sa.Column('byggar', sa.String(), nullable=False),
    sa.Column('fepilog', sa.String(), nullable=False),
    sa.Column('einflm', sa.String(), nullable=False),
    sa.Column('lod_flm', sa.String(), nullable=True),
    sa.Column('lod_flmein', sa.String(), nullable=True),
    sa.Column('fjherb', sa.String(), nullable=True),
    sa.Column('tegund', sa.String(), nullable=False),
    sa.Column('fullbuid', sa.String(), nullable=False),
    sa.Column('onothaefur_samningur', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('faerslunumer', 'fastnum', name=op.f('pk_hms_raw')),
    sa.UniqueConstraint('faerslunumer', 'fastnum', name='uq_raw_faerslunumer_fastnum'),
    schema='raw'
    )
    op.create_index(op.f('ix_raw_hms_raw_faerslunumer'), 'hms_raw', ['faerslunumer'], unique=False, schema='raw')
    op.create_unique_constraint('uq_faerslunumer_fastnum', 'hms', ['faerslunumer', 'fastnum'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_faerslunumer_fastnum', 'hms', type_='unique')
    op.drop_index(op.f('ix_raw_hms_raw_faerslunumer'), table_name='hms_raw', schema='raw')
    op.drop_table('hms_raw', schema='raw')
    op.execute("DROP SCHEMA IF EXISTS raw;")
    # ### end Alembic commands ###
