"""products, hms

Revision ID: 069b9c691fa6
Revises: f30fbf1f9396
Create Date: 2025-03-23 17:07:01.497094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '069b9c691fa6'
down_revision: Union[str, None] = 'f30fbf1f9396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hms',
    sa.Column('faerslunumer', sa.String(length=6), nullable=False),
    sa.Column('emnr', sa.String(length=3), nullable=False),
    sa.Column('skjalanumer', sa.String(length=13), nullable=False),
    sa.Column('fastnum', sa.String(length=7), nullable=False),
    sa.Column('heimilisfang', sa.String(length=255), nullable=True),
    sa.Column('postnr', sa.String(length=3), nullable=True),
    sa.Column('heinum', sa.String(length=7), nullable=True),
    sa.Column('svfn', sa.String(length=4), nullable=False),
    sa.Column('sveitarfelag', sa.String(length=255), nullable=False),
    sa.Column('utgdag', sa.DateTime(), nullable=False),
    sa.Column('thinglystdags', sa.DateTime(), nullable=False),
    sa.Column('kaupverd', sa.Integer(), nullable=False),
    sa.Column('fasteignamat', sa.Integer(), nullable=False),
    sa.Column('fasteignamat_gildandi', sa.Integer(), nullable=True),
    sa.Column('fyrirhugad_fasteignamat', sa.Integer(), nullable=True),
    sa.Column('brunabotamat_gildandi', sa.Integer(), nullable=True),
    sa.Column('byggar', sa.String(), nullable=False),
    sa.Column('fepilog', sa.String(length=6), nullable=False),
    sa.Column('einflm', sa.Numeric(), nullable=False),
    sa.Column('lod_flm', sa.String(), nullable=True),
    sa.Column('lod_flmein', sa.String(length=2), nullable=True),
    sa.Column('fjherb', sa.Integer(), nullable=True),
    sa.Column('tegund', sa.String(length=255), nullable=False),
    sa.Column('fullbuid', sa.Integer(), nullable=False),
    sa.Column('onothaefur_samningur', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('faerslunumer', 'fastnum', name=op.f('pk_hms')),
    sa.UniqueConstraint('faerslunumer', 'fastnum', name='uq_faerslunumer_fastnum')
    )
    op.create_index(op.f('ix_hms_faerslunumer'), 'hms', ['faerslunumer'], unique=False)
    op.create_index(op.f('ix_hms_skjalanumer'), 'hms', ['skjalanumer'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('cpu', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_manufacturer'), 'products', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_index(op.f('ix_products_year'), 'products', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_year'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_manufacturer'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_hms_skjalanumer'), table_name='hms')
    op.drop_index(op.f('ix_hms_faerslunumer'), table_name='hms')
    op.drop_table('hms')
    # ### end Alembic commands ###
